"""Table Creation

Revision ID: 99ff31a5fc6d
Revises: 
Create Date: 2023-02-02 10:12:03.296500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ff31a5fc6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('pet_id', sa.INTEGER(), nullable=False),
    sa.Column('pet_breed', sa.TEXT(), nullable=True),
    sa.Column('pet_name', sa.TEXT(), nullable=True),
    sa.Column('pet_owner', sa.TEXT(), nullable=True),
    sa.Column('pet_age', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.drop_table('toys')
    op.drop_table('owners')
    op.drop_table('pet')
    # ### end Alembic commands ###
